name: Test All Versions

# Continuously test this package with all versions of node on various OSes

on:
  push:
    branches-ignore:
      - 'npm-check-updates'
  pull_request:
  repository_dispatch:
  schedule:
    # Daily at 6:00am
    - cron: 0 6 * * *

jobs:
  test-matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        # There are problems on various architectures on lower versions that are more work to fix. Please open an issue if you need more version support
        node: [12, 13, 14, 15, 16]

    runs-on: ${{ matrix.os }}

    name: Node ${{ matrix.node }} on ${{ matrix.os }}

    steps:
      - name: Enable color for Npm output
        run: echo color = always >> .npmrc

      - name: Checkout latest code
        uses: actions/checkout@v1

      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: 'Debug: Node version'
        run: node --version

        # Install dependencies and Build

      - name: Install dependencies and Build using `npm install` to get latest non-breaking changes
        run: npm install

        # Test long usernames on Linux

      - name: Add long username and groupname for test
        if: runner.os == 'Linux'
        run: sudo useradd --user-group NameWithMoreThan15Chars

      - name: Test (with long names)
        run: npm test -- --color
        if: runner.os == 'Linux'
        env:
          TEST_LONG_USERNAME: NameWithMoreThan15Chars
          TEST_LONG_GROUPNAME: NameWithMoreThan15Chars

        # Don't test long usernames on macOS

      - name: Test (without long names)
        run: npm test -- --color
        if: runner.os == 'macOS'
